name: Build OpenWrt

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  BRANCH: main
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装编译依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils \
            rsync unzip zlib1g-dev file wget ccache

      - name: 下载 OpenWrt 源码
        run: |
          git clone --depth=1 $REPO_URL -b $BRANCH openwrt
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 复制自定义配置
        run: |
          cd openwrt
          cp $GITHUB_WORKSPACE/$CONFIG_FILE .config || make defconfig

      - name: 开始编译
        run: |
          cd openwrt
          make -j$(nproc) V=s

      - name: 上传固件
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt-Firmware
          path: openwrt/bin/targets/
